FROM php:8-apache

RUN a2enmod rewrite
COPY ./init.sh /usr/local/bin/init.sh
RUN chmod +x /usr/local/bin/init.sh

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

# Sound recording utilities
RUN apt-get update && apt-get upgrade --yes
RUN apt-get install --yes --no-install-recommends \
    sox alsa-utils libasound2-plugins

EXPOSE 80

