rhasspy:
  image: "rhasspy/rhasspy"
  container_name: rhasspy
  restart: unless-stopped
  volumes:
      - "$HOME/.config/rhasspy/profiles:/profiles"
      - "/etc/localtime:/etc/localtime:ro"
  ports:
      - "12101:12101"
      - "12183:12183"
  devices:
      # share the sound device
      - "/dev/snd:/dev/snd"
  command: --user-profiles /profiles --profile en
